jobs:
    - job: 'docker'
      pool:
          vmImage: 'ubuntu-16.04'
      container:
          image: $[variables.container]
          endpoint: $[variables.endpoint]
      strategy:
          matrix:
              CentOS5:
                  container: 'centos:5'
              CentOS6:
                  container: 'centos:6'
              CentOS7:
                  container: 'centos:7'
              Ubuntu1204:
                  container: 'ubuntu:12.04'
              Ubuntu1404:
                  container: 'ubuntu:14.04'
              Ubuntu1604:
                  container: 'ubuntu:16.04'
              Ubuntu1804:
                  container: 'ubuntu:18.04'
              DebianWheezy:
                  container: 'debian:wheezy'
              DebianJessie:
                  container: 'debian:jessie'
              DebianStretch:
                  container: 'debian:stretch'
              DebianBuster:
                  container: 'debian:buster'
              Manylinux1-686:
                  endpoint: quay.io
                  container: 'pypa/manylinux1_i686'
              Manylinux1-64:
                  endpoint: quay.io/
                  container: 'pypa/manylinux1_x86_64'
      steps:
          - script: 'echo "Success!"'
            displayName: echo in the container
