jobs:
    - job: 'docker'
      pool:
          vmImage: 'ubuntu-16.04'
      container: $[variables.container]
      strategy:
          matrix:
              CentOS5:
                  container: 'centos:5'
              CentOS6:
                  container: 'centos:6'
              CentOS7:
                  container: 'centos:7'
              UbuntuPrecise:
                  container: 'ubuntu:precise'
              UbuntuTrusty:
                  container: 'ubuntu:trusty'
              UbuntuXenial:
                  container: 'ubuntu:xenial'
              UbuntuBionic:
                  container: 'ubuntu:bionic'
              DebianWheezy:
                  container: 'debian:wheezy'
              DebianJessie:
                  container: 'debian:jessie'
              DebianStretch:
                  container: 'debian:stretch'
              DebianBuster:
                  container: 'debian:buster'
              Manylinux1-686:
                  container: 'quay.io/pypa/manylinux1_i686'
              Manylinux1-64:
                  container: 'quay.io/pypa/manylinux1_x86_64'
      steps:
          - script: 'echo "Success!"'
            displayName: echo in the container
